# Buddy pipeline - runs on develop branch merges
trigger:
  batch: true
  branches:
    include:
      - develop

parameters:
  - name: 'debug'
    displayName: '🐞 Enable debug output'
    type: boolean
    default: false

variables:
  - template: common-variables.yml
  - name: buildType
    value: Buddy

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates
  parameters:
    featureFlags:
      EnableCDPxPAT: false
      LinuxHostVersion:
        Network: KS3

    globalSdl:
      cg:
        failOnAlert: false
      tsa:
        enabled: false
      binskim:
        enabled: false
      policheck:
        enabled: false
      eslint:
        enabled: false

    stages:
      - template: common-validation-stage.yml@self
