/**
 * Seed Conversations Script
 * Creates test conversations with multiple messages for pagination testing
 *
 * Usage:
 *   npm run seed [mode] [count] [conversationId]
 *
 * Modes:
 *   batch   - Add messages in batch (fast, no AI responses) - default
 *   real    - Send messages and get real AI responses (slow)
 *
 * Arguments:
 *   mode           - 'batch' or 'real' (default: batch)
 *   count          - Number of message pairs to create (default: 20 for batch, 5 for real)
 *   conversationId - Optional: existing conversation ID to add messages to (must start with conv_)
 *
 * Examples:
 *   npm run seed                           # Batch: 20 message pairs, new conversation
 *   npm run seed batch 50                  # Batch: 50 message pairs, new conversation
 *   npm run seed batch 10 conv_abc123...   # Batch: 10 pairs to existing conversation
 *   npm run seed real 5                    # Real: 5 messages with AI responses
 *   npm run seed real 3 conv_abc123...     # Real: 3 messages to existing conversation
 */

import dotenv from "dotenv";
dotenv.config();

import { getAgentName, getOpenAIClient } from "../services/azureAI";

const TEST_MESSAGES = [
  "Hello, how are you?",
  "What's the weather like today?",
  "Tell me a joke",
  "What is the capital of France?",
  "How do I make pasta?",
  "Explain quantum computing",
  "What's 2 + 2?",
  "Tell me about AI",
  "How do I learn programming?",
  "What's the meaning of life?",
  "Recommend a good book",
  "How does the internet work?",
  "What's machine learning?",
  "Tell me about history",
  "How do airplanes fly?",
  "What's the largest ocean?",
  "Explain blockchain",
  "How do I stay healthy?",
  "What's the speed of light?",
  "Tell me a fun fact",
];

const MOCK_RESPONSES = [
  "I'm doing great, thanks for asking!",
  "The weather is sunny and pleasant today.",
  "Why did the programmer quit? Because they didn't get arrays!",
  "The capital of France is Paris.",
  "To make pasta, boil water, add pasta, cook for 8-10 minutes, drain and serve.",
  "Quantum computing uses quantum bits that can exist in superposition states.",
  "2 + 2 equals 4.",
  "AI is the simulation of human intelligence in machines.",
  "Start with Python, build projects, and practice daily!",
  "42, according to The Hitchhiker's Guide to the Galaxy.",
  "I recommend 'Sapiens' by Yuval Noah Harari.",
  "The internet connects computers through a global network of routers and servers.",
  "Machine learning is a subset of AI that learns from data patterns.",
  "History is the study of past events and human civilization.",
  "Airplanes fly due to lift generated by air flowing over wings.",
  "The Pacific Ocean is the largest ocean on Earth.",
  "Blockchain is a decentralized, distributed ledger technology.",
  "Stay healthy by exercising, eating well, and getting enough sleep.",
  "The speed of light is approximately 299,792,458 meters per second.",
  "Honey never spoils - archaeologists found 3000-year-old honey in Egyptian tombs!",
];

/**
 * Batch seed: Add messages directly to conversation items (fast, no AI)
 */
async function seedBatch(messageCount: number = 20, existingConversationId?: string) {
  console.log(`\n🌱 Batch seeding with ${messageCount} message pairs...\n`);

  try {
    const openAIClient = await getOpenAIClient();
    let conversationId: string;

    if (existingConversationId) {
      // Validate it's a real Azure conversation ID (not a local fake one)
      if (!existingConversationId.match(/^conv_[a-zA-Z0-9]{40,}/)) {
        console.error(`❌ Invalid conversation ID format: ${existingConversationId}`);
        console.error(`   Azure conversation IDs look like: conv_6277ed9d4779752300PEopnFljAhda5DVgdZGPWZ4wt4gpL2YA`);
        process.exit(1);
      }
      console.log(`📝 Using existing conversation: ${existingConversationId}`);
      conversationId = existingConversationId;
    } else {
      // Create a new conversation via Azure AI
      console.log("📝 Creating new conversation via Azure AI...");
      const conversation = await openAIClient.conversations.create({
        metadata: {
          title: `Test Batch Conversation - ${new Date().toISOString()}`,
          sessionId: "seed-script-batch",
        },
      });
      conversationId = conversation.id;
      
      // Validate the returned ID looks correct
      if (!conversationId.match(/^conv_[a-zA-Z0-9]{40,}/)) {
        console.error(`❌ Azure returned invalid conversation ID: ${conversationId}`);
        console.error(`   This might mean you're running against mock mode or there's an API issue.`);
        process.exit(1);
      }
      console.log(`✅ Created conversation: ${conversationId}`);
    }
    console.log();

    // Create message pairs in batches
    const BATCH_SIZE = 10;
    for (let batch = 0; batch < messageCount; batch += BATCH_SIZE) {
      const batchEnd = Math.min(batch + BATCH_SIZE, messageCount);
      const items: Array<{
        type: "message";
        role: "user" | "assistant";
        content: Array<{ type: "input_text"; text: string }>;
      }> = [];

      for (let i = batch; i < batchEnd; i++) {
        const userMsg = TEST_MESSAGES[i % TEST_MESSAGES.length];
        const assistantMsg = MOCK_RESPONSES[i % MOCK_RESPONSES.length];

        // Add user message
        items.push({
          type: "message",
          role: "user",
          content: [{ type: "input_text", text: `[Test ${i + 1}] ${userMsg}` }],
        });

        // Add assistant message (use input_text for both when adding to items)
        items.push({
          type: "message",
          role: "assistant",
          content: [{ type: "input_text", text: `[Response ${i + 1}] ${assistantMsg}` }],
        });
      }

      console.log(`📤 Adding batch ${batch / BATCH_SIZE + 1}: messages ${batch + 1}-${batchEnd}...`);

      try {
        // Cast to ResponseInputItem[] for SDK compatibility
        await openAIClient.conversations.items.create(conversationId, { 
          items: items as Parameters<typeof openAIClient.conversations.items.create>[1]["items"],
        });
        console.log(`✅ Batch added successfully\n`);
      } catch (err) {
        console.error(`❌ Failed to add batch:`, err);
      }
    }

    console.log(`\n✨ Done! Conversation ID: ${conversationId}`);
    console.log(`   Total messages: ${messageCount * 2} (${messageCount} user + ${messageCount} assistant)\n`);

    return conversationId;
  } catch (error) {
    console.error("❌ Failed to seed conversation:", error);
    process.exit(1);
  }
}

/**
 * Real seed: Send messages and get actual AI responses (slow)
 */
async function seedReal(messageCount: number = 5, existingConversationId?: string) {
  console.log(`\n🌱 Real seeding with ${messageCount} messages (with AI responses)...\n`);

  try {
    const openAIClient = await getOpenAIClient();
    const agentName = getAgentName();
    let conversationId: string;

    if (existingConversationId) {
      // Validate it's a real Azure conversation ID (not a local fake one)
      if (!existingConversationId.match(/^conv_[a-zA-Z0-9]{40,}/)) {
        console.error(`❌ Invalid conversation ID format: ${existingConversationId}`);
        console.error(`   Azure conversation IDs look like: conv_6277ed9d4779752300PEopnFljAhda5DVgdZGPWZ4wt4gpL2YA`);
        process.exit(1);
      }
      console.log(`📝 Using existing conversation: ${existingConversationId}`);
      conversationId = existingConversationId;
    } else {
      // Create a new conversation via Azure AI
      console.log("📝 Creating new conversation via Azure AI...");
      const conversation = await openAIClient.conversations.create({
        metadata: {
          title: `Test Real Conversation - ${new Date().toISOString()}`,
          sessionId: "seed-script-real",
        },
      });
      conversationId = conversation.id;
      
      // Validate the returned ID looks correct
      if (!conversationId.match(/^conv_[a-zA-Z0-9]{40,}/)) {
        console.error(`❌ Azure returned invalid conversation ID: ${conversationId}`);
        console.error(`   This might mean you're running against mock mode or there's an API issue.`);
        process.exit(1);
      }
      console.log(`✅ Created conversation: ${conversationId}`);
    }
    console.log();

    // Send messages one by one
    for (let i = 0; i < messageCount; i++) {
      const message = TEST_MESSAGES[i % TEST_MESSAGES.length];
      const messageNum = i + 1;

      console.log(`📤 [${messageNum}/${messageCount}] Sending: "${message.substring(0, 30)}..."`);

      try {
        const response = await openAIClient.responses.create(
          {
            input: `[Test ${messageNum}] ${message}`,
            conversation: conversationId,
            stream: false,
          },
          { body: { agent: { name: agentName, type: "agent_reference" } } },
        );

        // Extract response text from output_text field
        const responseText = response.output_text || "No response";
        console.log(`📥 [${messageNum}/${messageCount}] Response: "${responseText.substring(0, 50)}..."\n`);

        // Small delay to avoid rate limiting
        await new Promise((resolve) => setTimeout(resolve, 1000));
      } catch (err) {
        console.error(`❌ Failed to send message ${messageNum}:`, err);
      }
    }

    console.log(`\n✨ Done! Conversation ID: ${conversationId}`);
    console.log(`   Total messages: ${messageCount * 2} (${messageCount} user + ${messageCount} assistant)\n`);

    return conversationId;
  } catch (error) {
    console.error("❌ Failed to seed conversation:", error);
    process.exit(1);
  }
}

// Parse arguments
const args = process.argv.slice(2);
const mode = args[0] === "real" ? "real" : "batch";
const countArg = args[mode === "real" ? 1 : args[0] === "batch" ? 1 : 0];
const count = parseInt(countArg || (mode === "real" ? "5" : "20"), 10);
const conversationIdArg = args[mode === "real" ? 2 : args[0] === "batch" ? 2 : 1];
const conversationId = conversationIdArg?.startsWith("conv_") ? conversationIdArg : undefined;

console.log(`Mode: ${mode}, Count: ${count}${conversationId ? `, ConversationId: ${conversationId}` : " (new conversation)"}`);

if (mode === "real") {
  seedReal(count, conversationId);
} else {
  seedBatch(count, conversationId);
}
